// Auto-generated by scripts/sas-issuer-setup.ts — do not edit by hand.
// Maps known-wallet pubkey → on-chain attestation PDA. Used by the
// CardReveal + MintConfirm "✓ SAS-attested" badge so the RN client
// renders verification UX without doing crypto operations at runtime.

export type SasAttestationRecord = {
  pda: string;
  signature: string;
};

export const SAS_ATTESTATIONS: Record<string, SasAttestationRecord> = {
  '86xCnPeV69n6t3DnyGvkKobf9FdN2H9oiVDdaMpo2MMY': {
    pda: 'GBgxwC9AsgGp3kqoifQ79qs2EkZ3XP7wUQbyFDVAvo6x',
    signature: '2Npi6Sq2NtfNvh1C8iJRUbJzyi2edvsF8NQhqhRimk8ZEXKjQaDUcaCFVyWZk4d6XjvkqKa2tqR5mH158XZzq5Bb',
  },
  'E645TckHQnDcavVv92Etc6xSWQaq8zzPtPRGBheviRAk': {
    pda: '24vDZNW8ek5SvpafaYYP9brVQibUwHnT2vLzvyD7hear',
    signature: 'YWmQg35Kuo5s4ifpY5gfEvZK3nwVgNwRYfK3zBSkT5yu3FZTqkm3RWzyHc7zo484NBV8TXX8h6dN9EjcdNg4d7Q',
  },
  '2CiBfRKcERi2GgYn83UaGo1wFaYHHrXGGfnDaa2hxdEA': {
    pda: '6aEgESSmsTuftYTSAeuFWdiWExAxq7HQ9suewg5K66MC',
    signature: '57ittGP7riQb8b8JYmDKDBkGUTujdhkxfQWGpVzt3iiz2XPmmUotBC6D6nMgMaBZYhM3zJQrcs8GXp3meeYCYtvr',
  },
  'AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm': {
    pda: 'EavkcC1FUC9CKYSrfjUcx9ZdxcVtZwXbrhHEaJw7Pohb',
    signature: '4VX1d6i9VPRtGWSR1pGJXmCydu54WeA4bvMKadeBSzxHvvSRYLZLVkbfXB67gddfwfytpDGxJRKnR8LhYvHd7Rb8',
  },
  '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU': {
    pda: 'Fg4ac7SUHdfftSC4uWzWgWEGwXTHYsXrBR1RMPzGqzqc',
    signature: 'UH3VEgt9We5vRaMZpYjJ5BRYmDUwFLWzXiarFqy7QbsLs3wo27k1DQQh7qDqfWRBfa4rCNEdZmu8Gkdonw6GAAR',
  },
};

export function getSasAttestation(walletPubkey: string): SasAttestationRecord | null {
  return SAS_ATTESTATIONS[walletPubkey] ?? null;
}

export function hasSasAttestation(walletPubkey: string): boolean {
  return walletPubkey in SAS_ATTESTATIONS;
}
