// Auto-generated by scripts/sas-issuer-setup.ts — do not edit by hand.
// Re-run the script to regenerate. Schema layout + field names live
// in the script for ease of cross-reference; matched at runtime by
// sas-lib's serialize/deserialize layer.

export const SAS_PROGRAM_ID = '22zoJMtdu4tQc2PzL74ZUT7FrwgB1Udec8DdW4yw4BdG';
export const SAS_NETWORK = 'devnet';

export const SAS_ISSUER_PUBKEY = '6uRTvYnEWJNmDayu7unoyTjqCRyuENwWVUyEDjbbV8Wx';
export const SAS_CREDENTIAL_PDA = 'EUoMouVtQJFhaqf3aCErWCa3gkQ9QDawjeMfe33aiwKg';
export const SAS_SCHEMA_PDA = '4BAEmFLZaQE2QZAAeB64wTuLgXrWu1s1a98Wi9Aobji9';

export const SAS_SCHEMA_NAME = 'WRAP_IDENTITY_V1';
export const SAS_SCHEMA_VERSION = 1;

// Helpful URLs for README + judges:
export const sasSchemaSolscanUrl = (pda: string = SAS_SCHEMA_PDA) =>
  `https://solscan.io/account/${pda}?cluster=devnet`;
export const sasAttestationSolscanUrl = (pda: string) =>
  `https://solscan.io/account/${pda}?cluster=devnet`;
