// 7 card types — each is a "Wrapped" story for the user's wallet.
// Gradients vary per card type but all riff on the Solana red→violet core.

const CARDS = [
  {
    id: 'swaps',
    icon: 'fire',
    label: 'Top Tokens',
    stat: '142',
    statUnit: 'SWAPS',
    sub: 'in 2026',
    line: 'You held BONK through three 80% drawdowns. Iron stomach.',
    bg: 'linear-gradient(155deg, #FE3B68 0%, #FF6B3B 45%, #9945FF 100%)',
    accent: '#FFD93B',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'diamond',
    icon: 'diamond',
    label: 'Diamond Hand',
    stat: '847',
    statUnit: 'DAYS',
    sub: 'holding $JUP',
    line: 'You bought once. You never sold. Reverence levels: monastic.',
    bg: 'linear-gradient(160deg, #00E0FF 0%, #6B5BFF 50%, #9945FF 100%)',
    accent: '#FFFFFF',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'og',
    icon: 'crown',
    label: 'OG Status',
    stat: 'TOP 1%',
    statUnit: '',
    sub: 'wallet age: 4.2 yrs',
    line: 'You were here when SOL was three digits. Then two. Then three again.',
    bg: 'linear-gradient(170deg, #FFB800 0%, #FE3B68 55%, #9945FF 100%)',
    accent: '#0A0A0F',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'recap',
    icon: 'spiral',
    label: 'Year Recap',
    stat: '2026',
    statUnit: '',
    sub: 'on chain',
    line: '1,284 transactions. 47 protocols. 0 regrets. (Allegedly.)',
    bg: 'linear-gradient(180deg, #9945FF 0%, #FE3B68 60%, #FFB800 100%)',
    accent: '#FFFFFF',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'genre',
    icon: 'palette',
    label: 'Top Genre',
    stat: 'DEFI',
    statUnit: 'MAXI',
    sub: '68% of activity',
    line: 'Yields, vaults, and three-token LP positions. You read the docs.',
    bg: 'linear-gradient(145deg, #00FFB2 0%, #00B2FF 50%, #9945FF 100%)',
    accent: '#0A0A0F',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'personality',
    icon: 'mirror',
    label: 'Personality',
    stat: 'THE',
    statUnit: 'SCOUT',
    sub: 'archetype',
    line: 'First in, often early. You found 4 tokens before they had a logo.',
    bg: 'linear-gradient(135deg, #FE3B68 0%, #B23BFE 50%, #3B6BFE 100%)',
    accent: '#FFD93B',
    pubkey: '6uRT...V8Wx',
  },
  {
    id: 'achievement',
    icon: 'trophy',
    label: 'Achievements',
    stat: '12 / 20',
    statUnit: '',
    sub: 'badges earned',
    line: 'Liquidity Provider, Airdrop Farmer, NFT Survivor. Three new this year.',
    bg: 'linear-gradient(165deg, #FFB800 0%, #FE3B68 50%, #6B3BFE 100%)',
    accent: '#0A0A0F',
    pubkey: '6uRT...V8Wx',
  },
];

Object.assign(window, { CARDS });
